---
platform: linux

image_resource:
  type: docker-image
  source: { repository: betomorrow/docker-awsebcli }

inputs:
  - name: pipeline-src
  - name: api-artifact

run:
  path: pipeline-src/api/tasks/deploy.sh
